"""add language to posts

Revision ID: 304307ab9725
Revises: 0f4d9838255d
Create Date: 2020-04-04 11:42:45.894471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304307ab9725'
down_revision = '0f4d9838255d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
